### ISSUE TITLE
External websocket port does not work properly at Kubernetes with nginx, nginx-ingress and cert-manager

### ISSUE THREAD

**Issue by Shraa** [OmniDB/OmniDB#729]
When i run OmniDB in Kubernetes with nginx, nginx-ingress  and cert-manager i can't define external websocket port.
Deployment scheme:
User --> nginx-ingress with cert-manager--> nginx --> OmniDB server

Nginx configuration:
```
server {
    server_name omnidb.example.com;
    listen  80;
    listen [::]:80;

    proxy_send_timeout 120;
    proxy_read_timeout 300;
    proxy_buffering    off;
    keepalive_timeout  5 5;
    tcp_nodelay        on;

    location /wss {
        proxy_pass  http://omnidb:25482/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        proxy_pass http://omnidb:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

```
Nginx-ingress and cert-manager configuration:
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: omnidb.example.com-issuer
spec:
  acme:
    # The ACME production api URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: adm@scanex.ru
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: omnidb.example.com-issuer
    # Enable the HTTP-01 challenge provider
    http01: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: omnidb.example.com-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: omnidb.example.com-issuer
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - omnidb.example.com
    secretName: omnidb.example.com-ingress
  rules:
  - host: omnidb.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
```
Deckerfile CMD directive:
`CMD ["python3", "omnidb-server.py", "-H", "0.0.0.0", "-p", "5000", "-w", "25482", "-e", "443", "-d", "/data"]`

Each time when i logging-in to OmniDB i see message: "Cannot connect to websocket server with ports 443 (external) and 25482 (internal). Trying again in 5 seconds..."
